name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: javavirys/android:30.0.2
    steps:
      - name: Checkout Project
        uses: actions/checkout@v1

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: lint
        run: |
          ls
          ./gradlew lint

      - name: test
        run: |
          ./gradlew test

      - name: build
        run: |
          ./gradlew assemble